# global constants, imported to various files

NORTH = 1
SOUTH = 2
EAST = 3
WEST = 4

RED = (255,0,0)
BLUE = (0,0,255)
GREEN = (0,255,0)
YELLOW = (255,255,0)

COLORS = [RED, BLUE, GREEN, YELLOW]

CUTOFF_TIME = 60

SUCCESS = "SUCCESS"
DEPTH_CUTOFF = "DEPTH_CUTOFF"
TIME_CUTOFF = "TIME_CUTOFF"
FAILURE = "FAILURE"
